INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (11, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (19, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (27, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (40, 2);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (77, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (85, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (147, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (156, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (160, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (161, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (173, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (176, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (266, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (292, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (338, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (357, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (392, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (445, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (491, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (547, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (576, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (610, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (619, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (693, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (731, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (745, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (764, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (770, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (805, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (829, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (841, 3);
DELETE FROM public.gold_standard WHERE wp_id=869;
UPDATE public.word_pair SET active_status=0 WHERE id=869;
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (876, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (907, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (909, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (951, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (968, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (975, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (993, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1004, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1121, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1256, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1268, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1300, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1313, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1367, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1382, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1386, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1411, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1428, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1440, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1447, 1);
DELETE FROM public.gold_standard WHERE wp_id=1473;
UPDATE public.word_pair SET active_status=0 WHERE id=1473;
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1477, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1484, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1489, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1501, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1571, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1595, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1608, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1669, 3);
DELETE FROM public.gold_standard WHERE wp_id=1727;
UPDATE public.word_pair SET active_status=0 WHERE id=1727;
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1761, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1767, 1);
DELETE FROM public.gold_standard WHERE wp_id=1796;
UPDATE public.word_pair SET active_status=0 WHERE id=1796;
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1809, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1866, 3);
DELETE FROM public.gold_standard WHERE wp_id=1903;
UPDATE public.word_pair SET active_status=0 WHERE id=1903;
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (1953, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2043, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2074, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2093, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2141, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2142, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2158, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2172, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2204, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2230, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2253, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2265, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2319, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2404, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2407, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2422, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2427, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2466, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2520, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2599, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2612, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2614, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2622, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2667, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2721, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2730, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2749, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2782, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2793, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2803, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2813, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2822, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2894, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2936, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2954, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2983, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (2990, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3022, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3050, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3092, 1);
DELETE FROM public.gold_standard WHERE wp_id=3132;
UPDATE public.word_pair SET active_status=0 WHERE id=3132;
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3150, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3186, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3193, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3201, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3202, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3297, 1);
DELETE FROM public.gold_standard WHERE wp_id=3403;
UPDATE public.word_pair SET active_status=0 WHERE id=3403;
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3447, 3);
DELETE FROM public.gold_standard WHERE wp_id=3448;
UPDATE public.word_pair SET active_status=0 WHERE id=3448;
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3481, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3500, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3502, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3520, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3523, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3553, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3566, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3605, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3635, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3641, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3648, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3725, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3731, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3762, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3805, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3844, 3);
DELETE FROM public.gold_standard WHERE wp_id=3885;
UPDATE public.word_pair SET active_status=0 WHERE id=3885;
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3902, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3914, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3936, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (3979, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4025, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4049, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4051, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4066, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4072, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4116, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4131, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4213, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4229, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4321, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4323, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4445, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4519, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4556, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4630, 3);
DELETE FROM public.gold_standard WHERE wp_id=4635;
UPDATE public.word_pair SET active_status=0 WHERE id=4635;
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4639, 1);
DELETE FROM public.gold_standard WHERE wp_id=4657;
UPDATE public.word_pair SET active_status=0 WHERE id=4657;
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4683, 1);
DELETE FROM public.gold_standard WHERE wp_id=4717;
UPDATE public.word_pair SET active_status=0 WHERE id=4717;
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4750, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4790, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4813, 2);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4865, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4882, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4885, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (4979, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5001, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5012, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5018, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5038, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5143, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5155, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5215, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5251, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5256, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5265, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5279, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5298, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5300, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5313, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5417, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5427, 3);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5429, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5434, 1);
INSERT INTO public.gold_standard (wp_id, wrt_id) VALUES (5452, 1);
UPDATE public.annotation SET is_valid=false;
